### ISSUE TITLE
Problem working with Apache/PHP

### ISSUE THREAD

**Issue by zerowebcorp** [squash/gosendmail#1]
Hello

I've installed `gosendmail` on `/usr/sbin/gosendmail`. I've updated my php.ini and replaced `sendmail_path` with `/usr/sbin/gosendmail` 

Then created a test php file with one line of code to send an email. 

It works fine when I test it using command line
`php mail.php`

However, if I am opening the file using a browser, the mails are not being sent. `http://localhost/mail.php`

What could be the problem here ? Could you please help

**Comment by zerowebcorp** [comment]
Hi @squash  
Any help on this?

**Comment by zerowebcorp** [comment]
Found that it is because of incorrect permission of /tmp/gosendmail.log

**Comment by squash** [comment]
Awesome, that was going to be my first suggestion but you beat me to it!
